import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* client header with mobile menu */}
        <Header />

        {children}

        <footer className="site-footer">
          <div className="footer-inner">
            <nav className="footer-nav" aria-label="Footer">
              <a href="#">Attendace FAQ</a>
              <a href="#">Turntabl</a>
              <a href="#">Legal</a>
            </nav>
          </div>
        </footer>

      </body>
    </html>
  );
}
