import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="site-header">
          <div className="header-inner">
            <div className="header-left">
              <a href="#" className="logo">
                <img className="logo-icon" src="/FAQ-logo.svg" alt="" />
                <span className="logo-text">Attendace FAQ</span>
              </a>
            </div>

            <nav className="header-center">
              <a href="#">Home</a>
              <a href="#">Pricing</a>
              <a href="#">FAQ</a>
              <a href="#">Contact</a>
            </nav>

            <div className="header-right">
              <div className="search-wrapper">
                <input className="search-input" placeholder="Search FAQs" aria-label="Search FAQs" />
              </div>
              <button className="btn ghost">Login</button>
              <button className="btn solid">Sign Up</button>
            </div>

            <button className="hamburger" aria-label="Open menu">☰</button>
          </div>
        </header>

        {children}

        <footer className="site-footer">
          <div className="footer-inner">
            <nav className="footer-nav" aria-label="Footer">
              <a href="#">Attendace FAQ</a>
              <a href="#">Turntabl</a>
              <a href="#">Legal</a>
            </nav>
          </div>
        </footer>

      </body>
    </html>
  );
}
